### ISSUE TITLE
Feature Request: Add GitHub Workflow for Automatic Model Testing

### ISSUE THREAD

**Issue by lucas-vivier** [ESMAP-World-Bank-Group/EPM#30]
We’d like to add a **GitHub Actions workflow to automatically test the model on each commit or pull request.** The goal is to ensure that all code changes continue to produce a valid and working result using the test input data we’ve already included in the repository.

**Desired behavior:**
- On each commit or PR:
  - Launch GAMS with the current version of the model using the test input data
  - Run in a lightweight/test mode if needed (e.g., limited years or zones)
  - If the model fails (e.g., error code, missing output), the GitHub check fails

We’d appreciate suggestions or examples on how is it possible to do with GAMS code (we only have experiences with Python only code).

**Comment by JBroihan** [comment]
When we implement such workflows internally, we use our [official docker container](https://hub.docker.com/r/gams/gams) that has GAMS preinstalled. That could look as follows:

```
jobs:
  build:
    runs-on: ubuntu-latest
    # Use the GAMS Docker image for all steps in this job
    container:
      image: gams/gams:latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Inject GAMS license
        # use GitHub Secrets to temporarily store the GAMS License in the container.

      - name: Run GAMS model
        # Assuming main.gms is at the repository root
        run: gams main.gms < OPTIONS >
```

If the execution of the gams call fails, your workflow will fail.
